name: Wild
main: SkyLightMCPE\Main
version: 1.2
api: [3.0.0-ALPHA11, 3.0.0-ALPAH12, 4.0.0]
author: 
- SkyLightMCPE
website: https://github.com/SkyLightMCPE
commands:
 wild:
  usage: /wild 
  description: Teleports you in a random place without getting any fall damage if teleported in the air!
